### PR TITLE
Hdf corrupt

### LINKED ISSUE #137: Corrupted downloads not being detected and modis_collect appending these into the .collected files listing
When a download is corrupt, this is not detected (could be detected through the checksum that is in the .xml file that is sitting next to the .hdf)

When modis_collect finds a corrupt .hdf, it substitues with nodata:
image

Default behaviour should be to break when hitting a file that cannot be read

### PR DESCRIPTION
**Pull request by valpesendorfer**
Implements fail on corrupt HDF file + `force` flag as override

Closes #137 and #139

### CODE REVIEW

**Review by interob — COMMENTED** [review]
Single threaded collect will raise an IOError for corrupt HDF; multi-threaded will raise an AssertionError. Should this be harmonised?

**Comment by interob** [comment]
When MODAPE hits a corrupt HDF, the HDFs that actually have been collected do not make it into .collected

**Comment by interob** [comment]
Maybe ModisRawH5::update should:
* return a dict rather than a list: each filename has True/False for collected yes/no
* force would mean: abort on error, not raise an exception

Then, the exception is raised only in modis_collect. And after collected HDFs have been written to .collected

**Comment by valpesendorfer** [comment]
> Single threaded collect will raise an IOError for corrupt HDF; multi-threaded will raise an AssertionError. Should this be harmonised?

Are you referring to `modis_collect` line 166?

**Comment by valpesendorfer** [comment]
> When MODAPE hits a corrupt HDF, the HDFs that actually have been collected do not make it into .collected

Yes, when there's a corrupt HDF and the process fails, there will not be a .collected file because the collection process is considered failed (not incomplete)

**Comment by interob** [comment]
> > Single threaded collect will raise an IOError for corrupt HDF; multi-threaded will raise an AssertionError. Should this be harmonised?
> 
> Are you referring to `modis_collect` line 166?

Yes. So maybe better: `if future.exception() is not None: raise future.exception()`?

**Comment by interob** [comment]
> > When MODAPE hits a corrupt HDF, the HDFs that actually have been collected do not make it into .collected
> 
> Yes, when there's a corrupt HDF and the process fails, there will not be a .collected file because the collection process is considered failed (not incomplete)

I see. But still, there may be raw H5s that have been modified (by the collected HDFs); from that perspective, the process is incomplete rather than failed.

Can previously collected HDFs be re-collected? If so, then the current behaviour (considering the collection process failed) is fine with me.

**Comment by valpesendorfer** [comment]
> > > When MODAPE hits a corrupt HDF, the HDFs that actually have been collected do not make it into .collected
> > 
> > 
> > Yes, when there's a corrupt HDF and the process fails, there will not be a .collected file because the collection process is considered failed (not incomplete)
> 
> I see. But still, there may be raw H5s that have been modified (by the collected HDFs); from that perspective, the process is incomplete rather than failed.
> 
> Can previously collected HDFs be re-collected? If so, then the current behaviour (considering the collection process failed) is fine with me.

I'm just concerned with getting into a mess where some files are collected and maybe cleaned-up and some are not. 

In the current situation, you can just identify the corrupt file, replace and re-run the collect process. It should go fine - the only complication I could see is if there's some funky HDF5 business going on.

Also, there's one major drawback:

If you collect many tiles, one corrupt HDF file of one single tile will fail the entire process.

**Comment by interob** [comment]
> > > > When MODAPE hits a corrupt HDF, the HDFs that actually have been collected do not make it into .collected
> > > 
> > > 
> > > Yes, when there's a corrupt HDF and the process fails, there will not be a .collected file because the collection process is considered failed (not incomplete)
> > 
> > 
> > I see. But still, there may be raw H5s that have been modified (by the collected HDFs); from that perspective, the process is incomplete rather than failed.
> > Can previously collected HDFs be re-collected? If so, then the current behaviour (considering the collection process failed) is fine with me.
> 
> I'm just concerned with getting into a mess where some files are collected and maybe cleaned-up and some are not.
> 
> In the current situation, you can just identify the corrupt file, replace and re-run the collect process. It should go fine - the only complication I could see is if there's some funky HDF5 business going on.
> 
> Also, there's one major drawback:
> 
> If you collect many tiles, one corrupt HDF file of one single tile will fail the entire process.

IMO, failing the entire process is good. For example: a later modis_window call may straddle MODIS-tiles with differing collect status... This is no good.

As you are indicating: fixing the corrupt HDF and then re-doing the collect should work (recollecting previously collecting HDFs and actually collecting the corrupted one(s)) -- then I am happy with the current implementation (not recording collected .HDFs in the .collected trace in case of "partial" collecting). Let's agree here that we're not interested in partial collection success.

**Comment by interob** [comment]
I am happy if this PR gets merged in dev

**Comment by valpesendorfer** [comment]
Just requested a review, but saw that you already commented. For the sake of it, please approve then I'll merge

**Review by interob — APPROVED** [review]
This implementation does not record any collected HDF in the .collected trace file in case of partial success of the collection process with `force=True`; this is fine: we do not recognise a "partial collection success".

Should documentation indicate that modis_collect may raise an IOError when the `--force` flag is used?

**Comment by interob** [comment]
> This implementation does not record any collected HDF in the .collected trace file in case of partial success of the collection process with `force=True`; this is fine: we do not recognise a "partial collection success".
> 
> Should documentation indicate that modis_collect may raise an IOError when the `--force` flag is used?

Sorry, the other way around: when `--force` flag is NOT set

**Comment by valpesendorfer** [comment]
I've improved the docstring a bit to make it clear what `--force` does and does not. I don't think we need to go into deep detail which exception is raised - this is documented in the underlying API

**Review by interob — APPROVED** [review]

**Pull request merged**
