### PR TITLE
Fix recorded full paths for downloaded MODIS tiles

### PR DESCRIPTION
**Pull request by interob**

### CODE REVIEW

**Comment by valpesendorfer** [comment]
Thanks @interob - could you elaborate on your changes?

**Comment by interob** [comment]
line 207: the scenario of interupted download using aria2 sets files to an empty list
lines 211 and 235: upon successful download (either aria2 or download by plain request), the list is properly filled with correct path (this is a bug fix: list was filled with invalid paths because of a missing path separator in the concat of targetdir + fname)

**Comment by valpesendorfer** [comment]
What would be the upside of having an empty list in line `207`? Currently the file list has no active function, so there's also no issue with the invalid paths.

Rather than merging your changes into `master`, I would re-work the handling of paths with `pathlib` to increase compatibility for windows and merge it into a development branch for the next patch release

**Comment by interob** [comment]
Indeed, I see in your modis_download script you are not using the files list. However, in the production stack I am setting up, I need to use it.

If you have plans to code it differently, please go ahead. You could also merge for now, because you could also look at them as a bugfix rather than enhancement: there is some juggling with a file list going on, but it is not working.

**Comment by interob** [comment]
Regarding line 207 specifically: it looks like the `files` list is never modified before successful download by aria2, so you could indeed leave that one out of the patch: it's initialised to an empty list in the __init__ member already.

**Comment by valpesendorfer** [comment]
If you can use your own version that fixes the problem - I'd rather not merge anything into the master that's not a critical bugfix. Otherwise I need to create a new version, create the wheels, etc. ... So this will be implemented with a number of future enhancements

**Comment by interob** [comment]
I see. Are you thus leaving the concatenation of folder + filename as-is? That would then force me to update my fork with future changes in modape master. Although inconvenient, that's of course doable.

**Comment by valpesendorfer** [comment]
Would it be better if I create a development branch where these changes are reflected? This means any future master branch will include this changes, so no issues with that

**Comment by valpesendorfer** [comment]
I've created an issue #57 to record this, and it's already taken care of in the development branch, so it will be fixed in a future release.

Therefore I'm closing this PR.

Thanks!

**Pull request closed without merging**
