### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by valpesendorfer**
adds memfix - all checks passed

### CODE REVIEW

**Comment by interob** [comment]
Is our envisioned v1.0 affected by this issue? Are we sure that MODAPE produces the exact same results with this mem-optimizing tweak to the implementation?

**Comment by valpesendorfer** [comment]
@interob yes, hence the PR against v1.0rc. 

I've did a quick test which yielded the same results, plus all tests are passing. If you look at the code, it's really just a minor change. But not allocating the full weights array in `float64` saves a ton of memory.

**Comment by valpesendorfer** [comment]
Ready for merge

@interob could you review the changes and see if they are OK for you? This includes now some fixes, the date/tile check and fixed/improved testing

**Review by interob — APPROVED** [review]
Perfect

**Pull request merged**
