### PR TITLE
Including prints for search results

### PR DESCRIPTION
**Pull request by arnaldorusso**
This update brings information of all the files that `modape` will download.

### CODE REVIEW

**Comment by interob** [comment]
@arnaldorusso @valpesendorfer Maybe we want to go for `log.info()` rather than `print()`?

**Comment by interob** [comment]
@arnaldorusso By the way, did you notice the `--print-results` option that is already in the `modis_download` utility script?
https://github.com/WFP-VAM/modape/blob/8ad827a468ce4cc323119c9f20d229176936b70c/modape/scripts/modis_download.py#L27C25-L27C25

Maybe you think that printing needs improvement?
https://github.com/WFP-VAM/modape/blob/8ad827a468ce4cc323119c9f20d229176936b70c/modape/scripts/modis_download.py#L161

**Comment by ciclotux** [comment]
Humm, I see. Most of the time I use modape as a library, so before my download schedule I need to count the files and choose them following script criteria.
Since search() has no result output, printing was a simple solution for me.
If you suggest using log.info , what is the best way for moving forwards?
@interob

**Comment by arnaldorusso** [comment]
Humm, I see. Most of the time I use modape as a library, so before my download schedule I need to count the files and choose them following my script criteria.
Since search() has no result output, printing was a simple solution for me.
If you suggest using log.info , what is the best way for moving forwards in the way you could accept it?
@interob

**Comment by interob** [comment]
@arnaldorusso Well, actually we are discussing added echoing in the core routines. For these core routines, I'd like these to be able to operate silently. So actually, the current implementation with reporting search results in `scripts/modis_download.py` rather than `modis/download.py` is the best approach.

What stops you from inspecting the `results` property of the `ModisQuery` instance that you are working with in your own code? You can implement the reporting of search results in the same fashion as `scripts/modis_download.py` does:
https://github.com/WFP-VAM/modape/blob/8ad827a468ce4cc323119c9f20d229176936b70c/modape/scripts/modis_download.py#L27C25-L27C25

**Comment by arnaldorusso** [comment]
Ok, I didn’t notice that core routines were used for other scripts, and of course is yours team decision to return nothing or print results instead of silence.
In my own usage I want to see the files that will be downloaded and not only when it downloads or not. It’s because I don’t want to use scripts that are inside libs.
Of course I can use the query results (which I think so obscured and not very human readable) and for this reason I have asked in the issues section.
Anyway if you consider the search function to be silently, why turn it available and not use it internally and directly inside ModisQuery ? A clear output of ModisQuery would be much more usefull than the silent search() property.

**Comment by interob** [comment]
@arnaldorusso `search()` is a member function to ModisQuery and performs the actual search/querying against CMR and does so blocking. If not throwing any exception, it is thus successful and the `results` property on the ModisQuery holds the query results. It would indeed be nice for `search()` to directly return those same results; feel free to add a return statement to the `search` function; maybe in a new PR?

**Comment by interob** [comment]
Closing this PR: printing info should be optional and rather not in core routines.

**Pull request closed without merging**
