### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by valpesendorfer**
Going to merge all developments into the release candidate.

@interob how are we on things to fix/implement prior to release?

### CODE REVIEW

**Comment by interob** [comment]
My developments are aligned to the cutting-edge dev branch. So I am fine with merging into v1.0rc

(if that's what you are asking)

**Comment by valpesendorfer** [comment]
> My developments are aligned to the cutting-edge dev branch. So I am fine with merging into v1.0rc
> 
> (if that's what you are asking)

I was more wondering if there's anything else, besides what's in this PR, that needs to go into the RC before we do the actual release (and merge to master)

**Comment by interob** [comment]
I am thinking of some minor cosmetics, such as: adding timestamps to some key log.info and log.warning messages

**Comment by interob** [comment]
+ some click.echo messages

If you re OK with that?

**Comment by valpesendorfer** [comment]
> I am thinking of some minor cosmetics, such as: adding timestamps to some key log.info and log.warning messages

OK, I will go ahead and merge this one containing the major features. 

For small cosmetic things, you can prepare PRs straight against the RC (once #152 is merged) - new features as currently only against dev.

Looks like we're ready for release very soon! 🎉

**Comment by interob** [comment]
> > I am thinking of some minor cosmetics, such as: adding timestamps to some key log.info and log.warning messages
> 
> OK, I will go ahead and merge this one containing the major features.
> 
> For small cosmetic things, you can prepare PRs straight against the RC (once #152 is merged) - new features as currently only against dev.
> 
> Looks like we're ready for release very soon! 🎉

Awesome!

Great, will do the cosmetics against rc1

**Comment by interob** [comment]
I have given it some more thought: adding timestamps to the logging can of course be done through adjusting the logging format string (`logging.basicConfig`).

For `click.echo(...)` I can go with a monkey patch, redirecting the used-as-API scripts into a logger.

**Pull request merged**
