### PR TITLE
Modis window script tweaks and ModisMosaic::generate_mosaics returning list of filenames for mosaics/subsets

### PR DESCRIPTION
**Pull request by interob**
See https://github.com/WFP-VAM/modape/issues/119 and https://github.com/WFP-VAM/modape/issues/128

### CODE REVIEW

**Comment by valpesendorfer** [comment]
This PR is covering two separate issues, which is not ideal.

**Comment by interob** [comment]
Sorry, indeed it covers 2 issues:
- https://github.com/WFP-VAM/modape/issues/119
- https://github.com/WFP-VAM/modape/issues/128

**Comment by interob** [comment]
As discussed: check length of roi also when it is passed as list

**Review by valpesendorfer — CHANGES_REQUESTED** [review]
@interob please change the return types from `list` to `List`.

For adding `roi` as list and `gdal_kwarg` as dict, the typehints should also be changend in the function signature.

I'd recommend:

- `aoi`: `Union[str, List[float]]`
- `gdal_kwarg`:  `Union[Tuple[str], Dict[str, Union[str, int, float]]]`

**Comment by interob** [comment]
Just fixed those type hints

**Review by valpesendorfer — APPROVED** [review]

**Pull request merged**
