### PR TITLE
Fix issue of premature sending of Basic Auth info

### PR DESCRIPTION
**Pull request by interob**
#174

### CODE REVIEW

**Comment by interob** [comment]
Basically the Wiki's 2nd example of How To Access Data With Python is broken:
https://wiki.earthdata.nasa.gov/display/EL/How+To+Access+Data+With+Python
(The example is also referred to from here: https://stackoverflow.com/questions/58090630/cant-get-authorisation-to-work-with-python-requests#58126432)

**Comment by valpesendorfer** [comment]
ok looks like the checks passed on master, but next time I’d like to review 🙂

**Comment by interob** [comment]
Ouch, sorry! Got your question/instruction wrong

**Comment by interob** [comment]
OK, so for this time we leave the merging of your changes, right? My bad

**Pull request merged**
